apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: whoami-deployment
  namespace: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: whoami
    spec:
      containers:
        - image: containous/whoami
          name: whoami-container
          resources: {}
status: {}
